### ISSUE TITLE
通过 Git Submodules 管理源代码

### ISSUE THREAD

**Issue by calcitem** [hezhaoyun/chessroad-lite#2]
目前项目是复制了几个引擎的代码到版本库中，而上游引擎更新比较频繁，这样就可能会给代码同步带来不便。建议通过 Git Submodules 管理源代码。如果担心上游引入不必要的修改，可以考虑对每个引擎单独开分支维护，这样 git merge 也方便一些。另外，nnue 文件也考虑分离到独立的仓库维护，因为频繁更新这个二进制文件的话，主仓库可能会膨胀较快。

**Comment by hezhaoyun** [comment]
我没有使用过 Git Submodules 管理上游源代码，需要一些学习。
如果您愿意，请直接修改，然后发出 Pull Request！！

**Comment by calcitem** [comment]
好的，因为这个改动也有些大，所以不敢贸然做 PR，先提个 Issue 征询下老师意见。后续我做一下，然后将在 PR 中说明后续切换后如何更新和提交子模块的代码。

**Comment by calcitem** [comment]
老师可以帮忙先将那几个引擎的 GitHub 仓库 fork 到自己的账号下吗？最好是不勾选只克隆 main 分支，然后基于 main 或 master 分支创建 chessroad 分支。

**Comment by hezhaoyun** [comment]
谢谢您！方便的话加个及时通信方式吧，我的微信号：qq18718763

**Comment by hezhaoyun** [comment]
我已经依您的意思，fork 了相关的几个仓库

**Comment by calcitem** [comment]
完成。后续克隆主库后需要多执行一句 `git submodule update --init --recursive`，在子模块有更新时，执行 `git submodule update`
