### ISSUE TITLE
Stockfish 术语和命名风格

### ISSUE THREAD

**Issue by calcitem** [hezhaoyun/chessroad-lite#3]
目前基于 Stockfish 衍生的引擎不少，因此如果参考 Stockfish 的术语命名变量和函数的话，阅读起来感觉会更符合习惯。

有几个小建议：

step 重命名为 move，表示着法，棋步。

phase 重命名为 position，表示棋局，局面。一般 phase 是表示 opening/midgame/endgame 即开局、中局、残局三个阶段。

manual 重名名为 moveList，表示棋谱。

oppo 重命名为 them，表示对手，相对的，us 表示己方。sideToMove 表示行棋方。

kill 重名名为 checkmate，表示将死。

**Comment by pickaxe919** [comment]
同意大部分建议，棋谱一条可以再商榷：moveList仅表示着法序列，而manual还包含了棋谱的作者、对局者、对局时间、对局地点等信息。

**Comment by hezhaoyun** [comment]
@calcitem @pickaxe919 你两说的都很有道理，期待两位直接发 pull request!

**Comment by calcitem** [comment]
除了有争议的部分待调研，其他的我可以做 PR，因为这个改动太大，预估很容易出现冲突。估计棋路 Lite 刚上线近期可能会频繁改动，所以老师您如果有合适的时间窗就说声，我再提交。

**Comment by calcitem** [comment]
manual 除了谷歌翻译等翻译软件直接翻译出这个结果外，在其他网站上通过谷歌搜索 chess manual 找不到这个词，或是在正文中，被当做国际象棋教学手册了，怀疑英语里没有 "棋谱" 这个单词，所以翻译软件是硬翻译过来的。有待求证。

但是我还没找到更合适的词，感觉 record 貌似更接近一些。

**Comment by calcitem** [comment]
目前看来，"棋谱" 叫 "Game Notation" 更合适，参见：https://www.chessprogramming.org/Game_Notation

Game Notation refers to the recording of [moves](https://www.chessprogramming.org/Moves) of the chess game including players or programs names, date, name of event and site - in human competitive chess each side is required to fill and sign a [score sheet](https://en.wikipedia.org/wiki/Scoresheet_%28chess%29#Score_sheet). In official computer chess over the board [tournaments](https://www.chessprogramming.org/Tournaments_and_Matches), it was required for human operators as well, but was practically relaxed since programs keep their internal [move list](https://www.chessprogramming.org/Move_List) persistent and were able to restart for instance after a power failure [[1]](https://www.chessprogramming.org/Game_Notation#cite_note-1). In Chess [GUIs](https://www.chessprogramming.org/GUI), the game notation is presented inside a [notation window](https://www.chessprogramming.org/GUI#NotationWindow), which may allow certain interactions, like scrolling the list, or replaying the game.

**Comment by calcitem** [comment]
manual改为game notation，少部分改为move list.
